name: Global_System_Core
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
jobs:
  launch:
    runs-on: ubuntu-latest
    steps:
      - name: Preparing
        run: pip install python-telegram-bot groq
      - name: Ignite
        env:
          ENCODED_CORE: ${{ secrets.BOT_CODE_BASE64 }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: |
          echo $ENCODED_CORE | base64 -d > core.py
          python core.py
